[package]
name = "bitonic_soter"
version = "0.1.0"
authors = ["taronaldinho <kotaro.yamashita@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6"
rand_pcg = "0.1"